# Generated by Django 3.2 on 2021-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_categroy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('True', 'Availiabe in stock'), ('False', 'Not available in stock')], max_length=200),
        ),
    ]
